# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aggregation?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml